analyzers:
  mborg:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Monsterborg
    find_and_remove_prefix: 'mborg_base: '
    expected: ['mborg_base: battery_status','mborg_base: software_status']
    timeout: 5.0
