analyzers:
  husky:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Monsterborg
    find_and_remove_prefix: 'husky_base: '
    expected: ['husky_base: battery_status','husky_husky_base: software_status']
    timeout: 5.0
